(function(g){var window=this;var Npa=function(a,b){return g.Tb(a,b)},z5=function(){},Opa=function(a){if(a.zc&&"function"==typeof a.zc)return a.zc();
if(g.v(a))return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Pb(a)},Ppa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||g.v(a))(0,g.B)(a,b,void 0);else{if(a.Fd&&"function"==typeof a.Fd)var c=a.Fd();else if(a.zc&&"function"==typeof a.zc)c=void 0;else if(g.La(a)||g.v(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Qb(a);d=Opa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},A5=function(a){g.jn(a,"zx",g.dd());
return a},B5=function(a,b,c){g.Ka(c)||(c=[String(c)]);
g.on(a.l,b,c)},C5=function(a){return(a=g.Ko(a))?new ActiveXObject(a):new XMLHttpRequest},D5=function(a,b){return b+" ["+a.ba+" "+a.F+" "+a.getStatus()+"]"},Qpa=function(a){return"content-type"==a.toLowerCase()},E5=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.B&&(g.w.clearTimeout(a.B),a.B=null)},Rpa=function(a){return g.Od&&g.od(9)&&g.Ea(a.timeout)&&g.Ca(a.ontimeout)},F5=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},G5=function(a,b){if(a.g){E5(a);
var c=a.g,d=a.P[0]?g.Ga:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},H5=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;F5(a);G5(a)},I5=function(a){return a.g?a.g.readyState:0},J5=function(a){if(a.i&&"undefined"!=typeof g.AY)if(a.P[1]&&4==I5(a)&&2==a.getStatus())D5(a,"Local request error detected and ignored");
else if(a.D&&4==I5(a))g.Kg(a.Pv,0,a);else if(a.dispatchEvent("readystatechange"),4==I5(a)){D5(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Ug(String(a.F))[1]||null;if(!f&&g.w.self&&g.w.self.location){var k=g.w.self.location.protocol;f=k.substr(0,k.length-1)}e=!Spa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<I5(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";F5(a)}}finally{G5(a)}}},K5=function(a){g.Tf.call(this);
this.headers=new g.Ym;this.M=a||null;this.i=!1;this.P=this.g=null;this.ba=this.F="";this.u=0;this.l="";this.o=this.V=this.D=this.O=!1;this.A=0;this.B=null;this.Z="";this.I=this.R=!1},L5=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},Tpa=function(a,b){var c=[];
g.Wk(b,function(d){try{var e=g.Zo.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ca(e)?g.Yo(e)&&c.push(d):c.push(d)},a);
return c},Upa=function(a,b){var c=Tpa(a,b);
(0,g.B)(c,function(d){g.Zo.prototype.remove.call(this,d)},a)},M5=function(a){if(a.bd){if(a.bd.locationOverrideToken)return{locationOverrideToken:a.bd.locationOverrideToken};
if(null!=a.bd.latitudeE7&&null!=a.bd.longitudeE7)return{latitudeE7:a.bd.latitudeE7,longitudeE7:a.bd.longitudeE7}}return null},Vpa=function(a,b){g.Za(a,b)||a.push(b)},N5=function(a){var b=0,c;
for(c in a)b++;return b},O5=function(a,b){var c=b instanceof g.xc?b:g.Dc(b,/^data:image\//i.test(b));
a.src=g.yc(c)},Wpa=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))},Xpa=function(a){try{return g.w.JSON.parse(a)}catch(b){}a=String(a);
if(Wpa(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Ypa=function(a,b,c,d){var e=new g.an(null,void 0);
a&&g.bn(e,a);b&&g.cn(e,b);c&&g.dn(e,c);d&&(e.i=d);return e},P5=function(a){if(g.w.JSON)try{return g.w.JSON.parse(a)}catch(b){}return Xpa(a)},Q5=function(){this.g=[];
this.i=[]},R5=function(a,b){g.dq[a]=!0;
var c=g.bq();c&&c.publish.apply(c,arguments);g.dq[a]=!1},S5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Ym;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Zpa(this,a.capabilities||""),$pa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},Zpa=function(a,b){a.capabilities.clear();
(0,g.ae)(b.split(","),g.Qa(Npa,aqa)).forEach(function(c){a.capabilities.add(c)})},$pa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},T5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},U5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},V5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},bqa=function(a){return new T5(a)},W5=function(a){return g.Ka(a)?(0,g.G)(a,bqa):[]},X5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},Y5=function(a){return g.Ka(a)?"["+(0,g.G)(a,X5).join(",")+"]":"null"},Z5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},cqa=function(a){return(0,g.G)(a,function(b){return{key:b.id,
name:b.name}})},$5=function(a,b){return g.Wa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},a6=function(a,b){return g.Wa(a,function(c){return U5(c,b)})},dqa=function(){var a=(0,g.ut)();
a&&Upa(a,a.g.ff(!0))},b6=function(){var a=g.xt("yt-remote-connected-devices")||[];
g.pb(a);return a},eqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(d,e){return 0==e?d:d.substring(c.length)})},c6=function(a){g.wt("yt-remote-connected-devices",a,86400)},e6=function(){if(d6)return d6;
var a=g.xt("yt-remote-device-id");a||(a=Z5(),g.wt("yt-remote-device-id",a,31536E3));for(var b=b6(),c=1,d=a;g.Za(b,d);)c++,d=a+"#"+c;return d6=d},f6=function(){var a=b6(),b=e6();
g.Za(a,b);g.At()&&g.rb(a,b);a=eqa(a);if(0==a.length)try{g.Bs("remote_sid")}catch(c){}else try{g.xs("remote_sid",a.join(","),-1)}catch(c){}},g6=function(){return g.xt("yt-remote-session-browser-channel")},h6=function(){return g.xt("yt-remote-local-screens")||[]},i6=function(){g.wt("yt-remote-lounge-token-expiration",!0,86400)},fqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(h6(),function(d){return d.loungeToken}),c=(0,g.G)(a,function(d){return d.loungeToken});
(0,g.lj)(c,function(d){return!g.Za(b,d)})&&i6();
g.wt("yt-remote-local-screens",a,31536E3)},gqa=function(a,b){g.wt("yt-remote-session-browser-channel",a);
g.wt("yt-remote-session-screen-id",b);var c=b6(),d=e6();g.Za(c,d)||c.push(d);c6(c);f6()},j6=function(a){a||(g.zt("yt-remote-session-screen-id"),g.zt("yt-remote-session-video-id"));
f6();a=b6();g.bb(a,e6());c6(a)},l6=function(){if(!k6){var a=g.ip();
a&&(k6=new g.To(a))}return k6?!!k6.get("yt-remote-use-staging-server"):!1},m6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},n6=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},p6=function(a){a.length?o6(a.shift(),function(){p6(a)}):q6()},hqa=function(a){return"chrome-extension://"+a+r6},o6=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},q6=function(){var a=n6();
a&&a(!1,"No cast extension found")},s6=function(){if(iqa){var a=2,b=n6(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;o6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",q6,c)}},jqa=function(){s6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);p6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+r6,"//www.gstatic.com/eureka/clank"+r6])},t6=function(a,b,c){g.H.call(this);
this.A=null!=c?(0,g.y)(a,c):a;this.Vc=b;this.u=(0,g.y)(this.UC,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},u6=function(){},v6=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.A=d||1;this.o=45E3;this.aa=new g.pn(this);this.i=new g.Jg;this.i.setInterval(250)},x6=function(a,b,c){a.Sh=1;
a.eg=A5(b.clone());a.oh=c;a.u=!0;w6(a,null)},y6=function(a,b,c,d,e){a.Sh=1;
a.eg=A5(b.clone());a.oh=null;a.u=c;e&&(a.Iz=!1);w6(a,d)},w6=function(a,b){a.xi=(0,g.D)();
z6(a);a.yg=a.eg.clone();B5(a.yg,"t",a.A);a.Sk=0;a.tc=a.g.fp(a.g.Ik()?b:null);0<a.Kp&&(a.wn=new g.Jl((0,g.y)(a.QA,a,a.tc),a.Kp));a.aa.da(a.tc,"readystatechange",a.BL);var c=a.Tg?g.ac(a.Tg):{};a.oh?(a.eo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.tc.send(a.yg,a.eo,a.oh,c)):(a.eo="GET",a.Iz&&!g.Rd&&(c.Connection="close"),a.tc.send(a.yg,a.eo,null,c));a.g.pe(1)},G6=function(a,b,c){for(var d=!0;!a.Jg&&a.Sk<c.length;){var e=kqa(a,c);
if(e==A6){4==b&&(a.fg=4,B6(15),d=!1);break}else if(e==C6){a.fg=4;B6(16);d=!1;break}else D6(a,e)}4==b&&0==c.length&&(a.fg=1,B6(17),d=!1);a.ue=a.ue&&d;d||(E6(a),F6(a))},kqa=function(a,b){var c=a.Sk,d=b.indexOf("\n",c);
if(-1==d)return A6;c=Number(b.substring(c,d));if(isNaN(c))return C6;d+=1;if(d+c>b.length)return A6;var e=b.substr(d,c);a.Sk=d+c;return e},J6=function(a,b){a.xi=(0,g.D)();
z6(a);var c=b?window.location.hostname:"";a.yg=a.eg.clone();g.jn(a.yg,"DOMAIN",c);g.jn(a.yg,"t",a.A);try{a.ye=new ActiveXObject("htmlfile")}catch(n){E6(a);a.fg=7;B6(22);F6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in H6)k=H6[l];else if(l in I6)k=H6[l]=I6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
H6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Tc(g.qc("b/12014412"),d+"</body></html>");a.ye.open();a.ye.write(g.Nc(c));a.ye.close();a.ye.parentWindow.m=(0,g.y)(a.WK,a);a.ye.parentWindow.d=(0,g.y)(a.Oy,a,!0);a.ye.parentWindow.rpcClose=(0,g.y)(a.Oy,a,!1);c=a.ye.createElement("DIV");a.ye.parentWindow.document.body.appendChild(c);d=g.Cc(a.yg.toString());d=g.$c(g.zc(d));d=g.Tc(g.qc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Uc(c,d);a.g.pe(1)},z6=function(a){a.Qs=(0,g.D)()+a.o;
K6(a,a.o)},K6=function(a,b){if(null!=a.Oi)throw Error("WatchDog timer not null");
a.Oi=L6((0,g.y)(a.gL,a),b)},M6=function(a){a.Oi&&(g.w.clearTimeout(a.Oi),a.Oi=null)},F6=function(a){a.g.Nv()||a.Jg||a.g.fn(a)},E6=function(a){M6(a);
g.rf(a.wn);a.wn=null;a.i.stop();g.rn(a.aa);if(a.tc){var b=a.tc;a.tc=null;b.abort();b.dispose()}a.ye&&(a.ye=null)},D6=function(a,b){try{a.g.Iy(a,b),a.g.pe(4)}catch(c){}},O6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;N6(a,b,function(k){k?c(!0):g.w.setTimeout(function(){O6(a,b,c,d,f)},f)})}},N6=function(a,b,c){var d=new Image;
d.onload=function(){try{P6(d),c(!0)}catch(e){}};
d.onerror=function(){try{P6(d),c(!1)}catch(e){}};
d.onabort=function(){try{P6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{P6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
O5(d,a)},P6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Q6=function(a){this.g=a;
this.i=new u6},S6=function(a){var b=R6(a.g,a.Xi,"/mail/images/cleardot.gif");
A5(b);O6(b.toString(),5E3,(0,g.y)(a.fC,a),3,2E3);a.pe(1)},U6=function(a){var b=a.g.F;
if(null!=b)B6(5),b?(B6(11),T6(a.g,a,!1)):(B6(12),T6(a.g,a,!0));else if(a.Bd=new v6(a,void 0,void 0,void 0),a.Bd.Tg=a.Ip,b=a.g,b=R6(b,b.Ik()?a.Ej:null,a.Jp),B6(5),!g.Od||g.pd(10))B5(b,"TYPE","xmlhttp"),y6(a.Bd,b,!1,a.Ej,!1);else{B5(b,"TYPE","html");var c=a.Bd;a=!!a.Ej;c.Sh=3;c.eg=A5(b.clone());J6(c,a)}},V6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new u6;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},lqa=function(a,b){this.g=a;
this.map=b;this.context=null},W6=function(a){g.tf.call(this,"statevent",a)},X6=function(a,b){g.tf.call(this,"timingevent",a);
this.size=b},Y6=function(a){g.tf.call(this,"serverreachability",a)},b7=function(a){Z6(a);
if(3==a.g){var b=a.nk++,c=a.Tl.clone();g.jn(c,"SID",a.l);g.jn(c,"RID",b);g.jn(c,"TYPE","terminate");$6(a,c);b=new v6(a,a.l,b,void 0);b.Sh=2;b.eg=A5(c.clone());O5(new Image,b.eg.toString());b.xi=(0,g.D)();z6(b)}a7(a)},d7=function(a){a.xC(1,0);
a.Tl=R6(a,null,a.Hp);c7(a)},Z6=function(a){a.Vf&&(a.Vf.abort(),a.Vf=null);
a.Rb&&(a.Rb.cancel(),a.Rb=null);a.hf&&(g.w.clearTimeout(a.hf),a.hf=null);e7(a);a.xd&&(a.xd.cancel(),a.xd=null);a.ag&&(g.w.clearTimeout(a.ag),a.ag=null)},f7=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new lqa(a.gH++,b));2!=a.g&&3!=a.g||c7(a)},c7=function(a){a.xd||a.ag||(a.ag=L6((0,g.y)(a.Ny,a),0),a.Nh=0)},i7=function(a,b){if(1==a.g){if(!b){a.nk=Math.floor(1E5*Math.random());
var c=a.nk++,d=new v6(a,"",c,void 0);d.Tg=null;var e=g7(a),f=a.Tl.clone();g.jn(f,"RID",c);g.jn(f,"CVER","1");$6(a,f);x6(d,f,e);a.xd=d;a.g=2}}else 3==a.g&&(b?h7(a,b):0==a.i.length||a.xd||h7(a))},h7=function(a,b){if(b)if(6<a.Kg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.nk-1;var d=g7(a)}else c=b.B,d=b.oh;else c=a.nk++,d=g7(a);var e=a.Tl.clone();g.jn(e,"SID",a.l);g.jn(e,"RID",c);g.jn(e,"AID",a.bi);$6(a,e);c=new v6(a,a.l,c,a.Nh+1);c.Tg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.xd=c;x6(c,e,d)},$6=function(a,b){if(a.Tc){var c=a.Tc.ov();
c&&g.Jb(c,function(d,e){g.jn(b,e,d)})}},g7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Kg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Kg?e:f-d;try{g.Jb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},j7=function(a){a.Rb||a.hf||(a.B=1,a.hf=L6((0,g.y)(a.My,a),0),a.Hh=0)},l7=function(a){if(a.Rb||a.hf||3<=a.Hh)return!1;
a.B++;a.hf=L6((0,g.y)(a.My,a),k7(a,a.Hh));a.Hh++;return!0},T6=function(a,b,c){a.bo=c;
a.Ge=b.vf;a.A||d7(a)},e7=function(a){null!=a.Og&&(g.w.clearTimeout(a.Og),a.Og=null)},k7=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},n7=function(a,b){if(2==b||9==b){var c=null;
a.Tc&&(c=null);var d=(0,g.y)(a.fM,a);c||(c=new g.an("//www.google.com/images/cleardot.gif"),A5(c));N6(c.toString(),1E4,d)}else B6(2);m7(a,b)},m7=function(a,b){a.g=0;
a.Tc&&a.Tc.qu(b);a7(a);Z6(a)},a7=function(a){a.g=0;
a.Ge=-1;if(a.Tc)if(0==a.o.length&&0==a.i.length)a.Tc.To();else{g.fb(a.o);var b=g.fb(a.i);a.o.length=0;a.i.length=0;a.Tc.To(b)}},R6=function(a,b,c){var d=g.kn(c);
if(""!=d.g)b&&g.cn(d,b+"."+d.g),g.dn(d,d.u);else{var e=window.location;d=Ypa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.lj&&g.Jb(a.lj,function(f,k){g.jn(d,k,f)});
g.jn(d,"VER",a.Kg);$6(a,d);return d},L6=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},B6=function(a){o7.dispatchEvent(new W6(o7,a))},p7=function(){},mqa=function(a,b){this.action=a;
this.params=b||{}},q7=function(a,b){g.H.call(this);
this.g=new g.N(this.OK,0,this);g.I(this,this.g);this.Vc=5E3;this.i=0;if(g.Ma(a))b&&(a=(0,g.y)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.y)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},r7=function(a,b,c){this.H=a;
this.A=b;this.l=new g.So;this.i=new q7(this.KL,this);this.g=null;this.Za=!1;this.u=null;this.F="";this.D=this.o=0;this.B=[];this.I=c||!1},nqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.bo,sessionId:a.g.l,arrayId:a.g.bi}},s7=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&i7(a.g),b7(a.g));a.D=0},t7=function(a){return!!a.g&&3==a.g.g},oqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},u7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=g.Xg(a)||"";b&&(this.port=":"+b);this.domain=g.Wg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Gb(a,"10.0")&&(this.i=!1))},v7=function(a,b){var c=a.g;
if(g.Ca(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.fh(c+b,{})},w7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.o,d,!0),onError:g.Qa(a.l,e),pd:g.Qa(a.u,e)};c&&(a.rb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Wq(b,a)},pqa=function(){var a=x7;
y7();z7.push(a);A7(z7)},B7=function(a,b){y7();
var c=z7,d=qqa(a,String(b));0==c.length?rqa(d):(A7(c),(0,g.B)(c,function(e){e(d)}))},y7=function(){z7||(z7=g.x("yt.mdx.remote.debug.handlers_")||[],g.Fa("yt.mdx.remote.debug.handlers_",z7,void 0))},rqa=function(a){var b=(C7+1)%50;
C7=b;D7[b]=a;E7||(E7=49==b)},A7=function(a){var b=D7;
if(b[0]){var c=C7,d=E7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(f){f(e)})}while(d!=c);
D7=Array(50);C7=-1;E7=!1}},qqa=function(a,b){var c=((0,g.D)()-sqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},F7=function(a){g.Q.call(this);
this.B=a;this.g=[]},G7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},tqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.ae)(a.g,function(f){return!!$5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=G7(a,b[d])||c;return c},uqa=function(a,b){var c=a.g.length;
a.g=(0,g.ae)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},H7=function(a,b,c,d){g.Q.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},J7=function(a){F7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;I7(this);this.info("Initializing with "+Y5(this.g))},K7=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(d){return d.id}),c=v7(a.l,"/pairing/get_lounge_token_batch");
w7(a.l,c,{screen_ids:b.join(",")},(0,g.y)(a.eD,a),(0,g.y)(a.dD,a))}},I7=function(a){var b=W5(h6());
b=(0,g.ae)(b,function(c){return!c.uuid});
return tqa(a,b)},L7=function(a,b){fqa((0,g.G)(a.g,V5));
b&&i6()},N7=function(a,b){g.Q.call(this);
this.A=b;var c=g.xt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Za(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;M7("Initialized with "+g.Og(this.g))},O7=function(a,b,c){var d=v7(a.u,"/pairing/get_screen_availability");
w7(a.u,d,{lounge_token:b.token},(0,g.y)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.y)(function(){c(!1)},a))},P7=function(a,b){a:if(N5(b)!=N5(a.g))var c=!1;
else{c=g.Qb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(M7("Updated online screens: "+g.Og(a.g)),a.g=b,a.N("screenChange"));vqa(a)},Q7=function(a){isNaN(a.l)||g.aq(a.l);
a.l=g.Zp((0,g.y)(a.Rr,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},M7=function(a){B7("OnlineScreenService",a)},R7=function(a){var b={};
(0,g.B)(a.A(),function(c){c.token?b[c.token]=c.id:this.Jb("Requesting availability of screen w/o lounge token.")});
return b},vqa=function(a){a=g.Qb(g.Kb(a.g,function(b){return b}));
g.pb(a);a.length?g.wt("yt-remote-online-screen-ids",a.join(","),60):g.zt("yt-remote-online-screen-ids")},S7=function(a){F7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};wqa(this)},yqa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Hd();if(k=(c?a6(k,c):null)||a6(k,b)){k.uuid=b;var l=T7(a,k);O7(a.i,l,function(m){e(m?l:null)})}else c?xqa(a,c,(0,g.y)(function(m){var n=T7(this,new T5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));O7(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},zqa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},xqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={rb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Wq(v7(a.A,"/pairing/get_lounge_token_batch"),e)},Aqa=function(a){a.g=a.l.Hd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+Y5(a.g))},wqa=function(a){U7(a);
a.l=new J7(a.A);a.l.subscribe("screenChange",(0,g.y)(a.nD,a));Aqa(a);a.o=W5(g.xt("yt-remote-automatic-screen-cache")||[]);U7(a);a.info("Initializing automatic screens: "+Y5(a.o));a.i=new N7(a.A,(0,g.y)(a.Hd,a,!0));a.i.subscribe("screenChange",(0,g.y)(function(){this.N("onlineScreenChange")},a))},T7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=a6(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.wt("yt-remote-automatic-screen-cache",(0,g.G)(a.o,V5)));U7(a);a.u[b.uuid]=b.id;g.wt("yt-remote-device-id-map",a.u,31536E3);return b},U7=function(a){a.u=g.xt("yt-remote-device-id-map")||{}},V7=function(a,b,c){g.Q.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},W7=function(a,b){B7(a.P,b)},X7=function(a,b){V7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.y)(this.GM,this);this.u=(0,g.y)(this.rL,this);this.o=g.Zp((0,g.y)(function(){Bqa(this,null)},this),12E4)},Cqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Og(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ga,(0,g.y)(function(){W7(this,"Failed to send message: getMdxSessionStatus.")},a)):W7(a,"Sending yt message without session: "+g.Og(b))},Bqa=function(a,b){g.aq(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.y)(a.gn,a),d=(0,g.y)(a.Kd,a);a.Gv(b,c,d,5)}}else a.Kd(Error("Waiting for session status timed out."))},Y7=function(a,b,c){V7.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.B=g.Ga;this.A=NaN;this.I=(0,g.y)(this.JM,this);this.g=g.Ga},Dqa=function(a){a.g=a.F.VA(a.H,a.i.label,a.i.friendlyName,(0,g.y)(function(b){this.g=g.Ga;
this.gn(b)},a),(0,g.y)(function(b){this.g=g.Ga;
this.Kd(b)},a))},Eqa=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}l6()&&(b.env_useStageMdx=1);return g.dh(b)},Z7=function(a,b){V7.call(this,a,b,"ManualSession");
this.g=g.Zp((0,g.y)(this.di,this,null),150)},$7=function(a,b,c,d){g.Q.call(this);
this.i=a;this.B=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.y)(this.WJ,this)},Fqa=function(a,b){return b?g.Wa(a.l,function(c){return U5(b,c.label)},a):null},a8=function(a){B7("Controller",a)},x7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},b8=function(a){return a.u||!!a.l.length||!!a.g},c8=function(a,b,c){b!=a.g&&(g.rf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.y)(a.Ly,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.di(null)):a.N("yt-remote-cast2-session-change",null))},Gqa=function(a){var b=a.i.UA(),c=a.g&&a.g.i;
a=(0,g.G)(b,function(d){c&&U5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Fqa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Mqa=function(a,b,c,d,e,f,k){Hqa()?Iqa(b,e,f,k)&&(e8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Jqa(a,c):(window.__onGCastApiAvailable=function(l,m){l?Jqa(a,c):(f8("Failed to load cast API: "+m),g8(!1),e8(!1),g.zt("yt-remote-cast-available"),g.zt("yt-remote-cast-receiver"),Kqa(),c(!1))},d?g.lq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?jqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?q6():(s6(),p6(Lqa.map(hqa))))):d8("Cannot initialize because not running Chrome")},Kqa=function(){d8("dispose");
var a=h8();a&&a.dispose();g.Fa("yt.mdx.remote.cloudview.instance_",null,void 0);Nqa(!1);g.gq(i8);i8.length=0},j8=function(){return!!g.xt("yt-remote-cast-installed")},Oqa=function(){var a=g.xt("yt-remote-cast-receiver");
return a?a.friendlyName:null},Pqa=function(){d8("clearCurrentReceiver");
g.zt("yt-remote-cast-receiver")},Qqa=function(){return j8()?h8()?h8().getCastSession():(f8("getCastSelector: Cast is not initialized."),null):(f8("getCastSelector: Cast API is not installed!"),null)},l8=function(){j8()?h8()?k8()?(d8("Requesting cast selector."),h8().requestSession()):(d8("Wait for cast API to be ready to request the session."),i8.push(g.fq("yt-remote-cast2-api-ready",l8))):f8("requestCastSelector: Cast is not initialized."):f8("requestCastSelector: Cast API is not installed!")},m8=
function(a,b){k8()?h8().setConnectedScreenStatus(a,b):f8("setConnectedScreenStatus called before ready.")},Hqa=function(){var a=0<=g.Hb.search(/ (CrMo|Chrome|CriOS)\//);
return g.fx||a},Rqa=function(a,b){h8().init(a,b)},Iqa=function(a,b,c,d){var e=!1;
h8()||(a=new $7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.wt("yt-remote-cast-available",f);R5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){d8("onReceiverSelected: "+f.friendlyName);
g.wt("yt-remote-cast-receiver",f);R5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){d8("onReceiverResumed: "+f.friendlyName);
g.wt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){d8("onSessionChange: "+X5(f));
f||g.zt("yt-remote-cast-receiver");R5("yt-remote-cast2-session-change",f)}),g.Fa("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
d8("cloudview.createSingleton_: "+e);return e},h8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},Jqa=function(a,b){g8(!0);
e8(!1);Rqa(a,function(c){c?(Nqa(!0),g.iq("yt-remote-cast2-api-ready")):(f8("Failed to initialize cast API."),g8(!1),g.zt("yt-remote-cast-available"),g.zt("yt-remote-cast-receiver"),Kqa());b(c)})},d8=function(a){B7("cloudview",a)},f8=function(a){B7("cloudview",a)},g8=function(a){d8("setCastInstalled_ "+a);
g.wt("yt-remote-cast-installed",a)},k8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},Nqa=function(a){d8("setApiReady_ "+a);
g.Fa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},e8=function(a){g.Fa("yt.mdx.remote.cloudview.initializing_",a,void 0)},n8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.B=0;this.g=null;this.hasNext=this.Ie=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},o8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Ie=!1;a.hasNext=!1;a.B=0;a.A=(0,g.D)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},p8=function(a){return 1==a.playerState?((0,g.D)()-a.A)/1E3:0},q8=function(a,b){a.B=b;
a.A=(0,g.D)()},r8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.A)/1E3+a.B;
case -1E3:return 0}return a.B},s8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&o8(a)},t8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.bc(a.g);b.hasPrevious=a.Ie;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},v8=function(a,b){g.Q.call(this);
this.g=0;this.o=a;this.A=[];this.u=new Q5;this.l=this.i=null;this.F=(0,g.y)(this.QH,this);this.B=(0,g.y)(this.qk,this);this.D=(0,g.y)(this.PH,this);this.H=(0,g.y)(this.cI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ts,this),Sqa(this))):c=3;0!=c&&(b?this.Ts(c):g.Zp((0,g.y)(function(){this.Ts(c)},this),0));
var d=Qqa();d&&u8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},w8=function(a){return new n8(a.o.getPlayerContextData())},Sqa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Qa(this.TJ,b),this))},a)},Tqa=function(a){(0,g.B)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},x8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},z8=function(a,b,c){var d=w8(a);
q8(d,c);-1E3!=d.playerState&&(d.playerState=b);y8(a,d)},A8=function(a,b,c){a.o.sendMessage(b,c)},y8=function(a,b){Tqa(a);
a.o.setPlayerContextData(t8(b));Sqa(a)},u8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.B),a.qk(null));
a.l=b;a.l&&(B7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.B),a.l.media.length&&a.qk(a.l.media[0]))},Uqa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=w8(a);b.contentId!=d.videoId&&B7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;q8(d,a.i.getEstimatedTime());y8(a,d)}else B7("CP","No cast media video. Ignoring state update.")},B8=function(a,b,c){return(0,g.y)(function(d){this.Jb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Jb("Retrying "+b+" using MDx browser channel."),A8(this,b,c))},a)},C8=function(a,b,c){g.Q.call(this);
this.u=NaN;this.M=!1;this.H=this.F=this.I=this.P=NaN;this.O=[];this.o=this.B=this.l=this.Qa=this.g=null;this.na=a;this.O.push(g.cs(window,"beforeunload",(0,g.y)(this.XC,this)));this.i=[];this.Qa=new n8;this.V=b.id;this.g=Vqa(this,c);this.g.subscribe("handlerOpened",this.UH,this);this.g.subscribe("handlerClosed",this.RH,this);this.g.subscribe("handlerError",this.SH,this);this.g.subscribe("handlerMessage",this.TH,this);oqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Qa.videoId;
g.At()&&g.wt("yt-remote-session-video-id",d)},this)},D8=function(a){B7("conn",a)},Vqa=function(a,b){return new r7(v7(a.na,"/bc"),b)},E8=function(a,b){a.N("proxyStateChange",b)},Wqa=function(a){a.u=g.Zp((0,g.y)(function(){D8("Connecting timeout");
this.A(1)},a),2E4)},F8=function(a){g.aq(a.u);
a.u=NaN},G8=function(a){g.aq(a.P);
a.P=NaN},Xqa=function(a){H8(a);
a.I=g.Zp((0,g.y)(function(){I8(this,"getNowPlaying")},a),2E4)},H8=function(a){g.aq(a.I);
a.I=NaN},Zqa=function(a,b){b&&(F8(a),G8(a));
b==(t7(a.g)&&isNaN(a.u))?b&&(E8(a,1),I8(a,"getSubtitlesTrack")):b?(a.R()&&a.Qa.reset(),E8(a,1),I8(a,"getNowPlaying"),Yqa(a)):a.A(1)},$qa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Qa.videoId&&(g.Wb(b.params)?a.Qa.g=null:a.Qa.g=b.params,a.N("remotePlayerChange"))},ara=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Qa.listId=b.params.listId||a.Qa.listId;s8(a.Qa,c,d);a.N("remoteQueueChange")},cra=function(a,b){b.params=b.params||{};
ara(a,b);bra(a,b);a.N("autoplayDismissed")},bra=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
q8(a.Qa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Qa.playerState&&(c=-1E3);a.Qa.playerState=c;c=Number(b.params.loadedTime);a.Qa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Qa.D=isNaN(c)?0:c;c=a.Qa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Qa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Qa.playerState?Xqa(a):H8(a);a.N("remotePlayerChange")},dra=function(a,b){if(-1E3!=
a.Qa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Qa.playerState=c;c=parseInt(b.params.currentTime,10);q8(a.Qa,isNaN(c)?0:c);a.N("remotePlayerChange")}},era=function(a,b){var c="true"==b.params.muted;
a.Qa.volume=parseInt(b.params.volume,10);a.Qa.muted=c;a.N("remotePlayerChange")},fra=function(a,b){a.B=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},gra=function(a,b){var c="true"==b.params.hasNext;
a.Qa.Ie="true"==b.params.hasPrevious;a.Qa.hasNext=c;a.N("previousNextChange")},Yqa=function(a){g.aq(a.H);
a.H=g.Zp((0,g.y)(a.A,a,1),864E5)},I8=function(a,b,c){c?D8("Sending: action="+b+", params="+g.Og(c)):D8("Sending: action="+b);
a.g.sendMessage(b,c)},J8=function(a){F7.call(this,"ScreenServiceProxy");
this.Hc=a;this.i=[];this.i.push(this.Hc.$_s("screenChange",(0,g.y)(this.EM,this)));this.i.push(this.Hc.$_s("onlineScreenChange",(0,g.y)(this.xJ,this)))},lra=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Rp("MDX_CONFIG")||b;dqa();f6();K8||(K8=new u7(b?b.loungeApiHost:void 0),l6()&&(K8.g="/api/loungedev"));L8||(L8=g.x("yt.mdx.remote.deferredProxies_")||[],g.Fa("yt.mdx.remote.deferredProxies_",L8,void 0));hra();var c=M8();if(!c){var d=new S7(K8);g.Fa("yt.mdx.remote.screenService_",d,void 0);c=M8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Mqa(a,d,function(m){m?N8()&&m8(N8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){R5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Fa("yt.mdx.remote.initialized_",!0,void 0),O8("Initializing: "+g.Og(b)),P8.push(g.fq("yt-remote-cast2-availability-change",function(){R5("yt-remote-receiver-availability-change")})),P8.push(g.fq("yt-remote-cast2-receiver-selected",function(){Q8(null);
R5("yt-remote-auto-connect","cast-selector-receiver")})),P8.push(g.fq("yt-remote-cast2-receiver-resumed",function(){R5("yt-remote-receiver-resumed","cast-selector-receiver")})),P8.push(g.fq("yt-remote-cast2-session-change",ira)),P8.push(g.fq("yt-remote-connection-change",function(m){m?m8(N8(),"YouTube TV"):R8()||(m8(null,null),Pqa())})),a=S8(),b.isAuto&&(a.id+="#dial"),g.Nq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),O8(" -- with channel params: "+
g.Og(a)),jra(a),c.start(),N8()||kra())},nra=function(){var a=mra();
j8()&&g.xt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},mra=function(){var a=M8().Hc.$_gos();
var b=T8();b&&U8()&&($5(a,b)||a.push(b));return cqa(a)},V8=function(){var a=ora();
!a&&j8()&&Oqa()&&(a={key:"cast-selector-receiver",name:Oqa()});return a},ora=function(){var a=mra(),b=T8();
b||(b=R8());return g.Wa(a,function(c){return b&&U5(b,c.key)?!0:!1})},T8=function(){var a=N8();
if(!a)return null;var b=M8().Hd();return a6(b,a)},ira=function(a){O8("remote.onCastSessionChange_: "+X5(a));
if(a){var b=T8();b&&b.id==a.id?m8(b.id,"YouTube TV"):(b&&W8(),X8(a,1))}else U8()&&W8()},W8=function(){k8()?h8().stopSession():f8("stopSession called before API ready.");
var a=U8();a&&(a.disconnect(1),Y8(null))},Z8=function(){var a=U8();
return!!a&&3!=a.getProxyState()},O8=function(a){B7("remote",a)},M8=function(){if(!$8){var a=g.x("yt.mdx.remote.screenService_");
$8=a?new J8(a):null}return $8},N8=function(){return g.x("yt.mdx.remote.currentScreenId_")},pra=function(a){g.Fa("yt.mdx.remote.currentScreenId_",a,void 0)},qra=function(){return g.x("yt.mdx.remote.connectData_")},Q8=function(a){g.Fa("yt.mdx.remote.connectData_",a,void 0)},U8=function(){return g.x("yt.mdx.remote.connection_")},Y8=function(a){var b=U8();
Q8(null);a||pra("");g.Fa("yt.mdx.remote.connection_",a,void 0);L8&&((0,g.B)(L8,function(c){c(a)}),L8.length=0);
b&&!a?R5("yt-remote-connection-change",!1):!b&&a&&R5("yt-remote-connection-change",!0)},R8=function(){var a=g.At();
if(!a)return null;var b=M8().Hd();return a6(b,a)},X8=function(a,b){T8()&&T8();
pra(a.id);var c=new C8(K8,a,S8());c.connect(b,qra());c.subscribe("beforeDisconnect",function(d){R5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){U8()&&Y8(null)});
Y8(c)},kra=function(){var a=R8();
a?(O8("Resume connection to: "+X5(a)),X8(a,0)):(j6(),Pqa(),O8("Skipping connecting because no session screen found."))},hra=function(){var a=S8();
if(g.Wb(a)){a=e6();var b=g.xt("yt-remote-session-name")||"",c=g.xt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Fa("yt.mdx.remote.channelParams_",a,void 0)}},S8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},jra=function(a){a?(g.wt("yt-remote-session-app",a.app),g.wt("yt-remote-session-name",a.name)):(g.zt("yt-remote-session-app"),g.zt("yt-remote-session-name"));
g.Fa("yt.mdx.remote.channelParams_",a,void 0)},a9=function(a,b,c){g.H.call(this);
this.u=a;this.i=b;this.l=new g.Ls(this);g.I(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.OI);this.l.K(b,"captionschanged",this.OH);this.l.K(b,"captionssettingschanged",this.iA);this.l.K(b,"videoplayerreset",this.hn);this.l.K(b,"mdxautoplaycancel",this.eC);this.O=this.l.K(b,"onVolumeChange",this.vy);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Hy,this);c.subscribe("remotePlayerChange",this.tk,this);c.subscribe("remoteQueueChange",this.hn,this);c.subscribe("autoplayUpNext",this.iy,
this);c.subscribe("previousNextChange",this.Ey,this);c.subscribe("nowAutoplaying",this.Ay,this);c.subscribe("autoplayDismissed",this.hy,this);this.suggestion=null;this.F=new g.zC(64);this.o=new g.N(this.gA,500,this);g.I(this,this.o);this.A=new g.N(this.hA,1E3,this);g.I(this,this.A);this.I=new t6(this.oM,0,this);g.I(this,this.I);this.B={};this.P=new g.N(this.HA,1E3,this);g.I(this,this.P);this.H=new g.Jl(this.uF,1E3,this);g.I(this,this.H);this.M=g.Ga;this.iA();this.hn();this.tk()},b9=function(a,b){a.u.qd(b,
a.i.getVideoData().lengthSeconds)},rra=function(a){b9(a,0);
a.o.stop();c9(a,new g.zC(64))},e9=function(a,b){if(d9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.dc(c,b));a.g.Wz(a.i.getVideoData(1).videoId,c);a.B=w8(a.g).g}},f9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Sa;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.xf,M5(c));c9(a,new g.zC(1))},sra=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{aQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},d9=function(a){return w8(a.g).videoId==a.i.getVideoData(1).videoId},c9=function(a,b){a.A.stop();
var c=a.F;if(!g.FC(c,b)){var d=g.T(b,2);d!=g.T(a.F,2)&&g.tK(a.i,d);a.F=b;tra(a.u,c,b)}},g9=function(a){g.V.call(this,{C:"div",
G:"ytp-remote",J:[{C:"div",G:"ytp-remote-display-status",J:[{C:"div",G:"ytp-remote-display-status-icon",J:[g.EP()]},{C:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.oQ(this,250);g.I(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);ura(this,g.pK(a))},ura=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.DN("Error on $RECEIVER_NAME",c):g.GC(b)||g.T(b,4)?g.DN("Playing on $RECEIVER_NAME",c):g.DN("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},h9=function(a,b){g.WT.call(this,"Play on",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},i9=function(a){g.TK.call(this,a);
this.i={key:Z5(),name:"This computer"};this.o=null;this.u=[];this.B=this.g=null;this.A=[this.i];this.l=this.i;this.bk=new g.zC(64);this.D=0;this.ym=-1;if(!g.kz(g.X(this.player))){a=this.player;var b=g.sD(a);b&&(b=b.Rm())&&(b=new h9(a,b),g.I(this,b));b=new g9(a);g.I(this,b);g.FK(a,b.element,4)}},tra=function(a,b,c){a.bk=c;
a.player.N("presentingplayerstatechange",new g.GD(c,b))},j9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)W8();
else{a.l=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.xf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=M5(d))&&(c.locationInfo=d);d=c}else d=null;O8("Connecting to: "+g.Og(b));"cast-selector-receiver"==b.key?
(Q8(d||null),k8()?h8().setLaunchParams(d||null):f8("setLaunchParams called before ready.")):!d&&Z8()&&N8()==b.key?R5("yt-remote-connection-change",!0):(W8(),Q8(d||null),d=M8().Hd(),(d=a6(d,b.key))&&X8(d,1))}},Spa=/^https?$/i,vra=["POST",
"PUT"];g.A(K5,g.Tf);g.h=K5.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.u=0;this.ba=b;this.O=!1;this.i=!0;this.g=this.M?C5(this.M):C5(g.XY);this.P=this.M?this.M.getOptions():g.XY.getOptions();this.g.onreadystatechange=(0,g.y)(this.Pv,this);try{z5(D5(this,"Opening Xhr")),this.V=!0,this.g.open(b,String(a),!0),this.V=!1}catch(f){z5(D5(this,"Error opening Xhr: "+f.message));H5(this,f);return}a=c||
"";var e=this.headers.clone();d&&Ppa(d,function(f,k){e.set(k,f)});
d=g.Wa(e.Fd(),Qpa);c=g.w.FormData&&a instanceof g.w.FormData;!g.Za(vra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Z&&(this.g.responseType=this.Z);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{E5(this),0<this.A&&(this.I=Rpa(this.g),z5(D5(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.y)(this.Qv,this)):this.B=g.Kg(this.Qv,this.A,this)),z5(D5(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){z5(D5(this,"Send error: "+f.message)),H5(this,f)}};
g.h.Qv=function(){"undefined"!=typeof g.AY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,D5(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(D5(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),G5(this))};
g.h.T=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),G5(this,!0));K5.Ha.T.call(this)};
g.h.Pv=function(){this.ea()||(this.V||this.D||this.o?J5(this):this.VJ())};
g.h.VJ=function(){J5(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<I5(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.v(this.l)?this.l:String(this.l)};
var I6={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},H6={"'":"\\'"},wra={};g.h=Q5.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.Za(this.g,a)||g.Za(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Cma)(b,a);0<=c?(g.ab(b,c),b=!0):b=!1;return b||g.bb(this.i,a)};
g.h.zc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var aqa={dN:"atp",oP:"ska",dP:"que",CO:"mus",nP:"sus",TN:"dsp",kP:"seq"};S5.prototype.Wf=function(){var a=new S5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var k6,d6="",r6=m6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",iqa=m6("loadCastFramework")||m6("loadCastApplicationFramework"),Lqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(t6,g.H);g.h=t6.prototype;g.h.TC=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.D)()+this.Vc:this.za=g.Kg(this.u,this.Vc)};
g.h.stop=function(){this.za&&(g.w.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.T=function(){this.stop();t6.Ha.T.call(this)};
g.h.UC=function(){this.l?(this.za=g.Kg(this.u,this.l-(0,g.D)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};u6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
u6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=v6.prototype;g.h.Tg=null;g.h.ue=!1;g.h.Oi=null;g.h.Qs=null;g.h.xi=null;g.h.Sh=null;g.h.eg=null;g.h.yg=null;g.h.oh=null;g.h.tc=null;g.h.Sk=0;g.h.ye=null;g.h.eo=null;g.h.fg=null;g.h.Fj=-1;g.h.Iz=!0;g.h.Jg=!1;g.h.Kp=0;g.h.wn=null;var C6={},A6={};g.h=v6.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.BL=function(a){a=a.target;var b=this.wn;b&&3==I5(a)?b.Bj():this.QA(a)};
g.h.QA=function(a){try{if(a==this.tc)a:{var b=I5(this.tc),c=this.tc.u,d=this.tc.getStatus();if(g.Od&&!g.pd(10)||g.Rd&&!g.od("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Fh&&!L5(this.tc))break a;this.Jg||4!=b||7==c||(8==c||0>=d?this.g.pe(3):this.g.pe(2));M6(this);var e=this.tc.getStatus();this.Fj=e;var f=L5(this.tc);(this.ue=200==e)?(4==b&&E6(this),this.u?(G6(this,b,f),g.Fh&&this.ue&&3==b&&(this.aa.da(this.i,"tick",this.xL),this.i.start())):D6(this,f),this.ue&&!this.Jg&&(4==b?this.g.fn(this):(this.ue=
!1,z6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.fg=3,B6(13)):(this.fg=0,B6(14)),E6(this),F6(this))}}catch(k){this.tc&&L5(this.tc)}finally{}};
g.h.xL=function(){var a=I5(this.tc),b=L5(this.tc);this.Sk<b.length&&(M6(this),G6(this,a,b),this.ue&&4!=a&&z6(this))};
g.h.WK=function(a){L6((0,g.y)(this.VK,this,a),0)};
g.h.VK=function(a){this.Jg||(M6(this),D6(this,a),z6(this))};
g.h.Oy=function(a){L6((0,g.y)(this.UK,this,a),0)};
g.h.UK=function(a){this.Jg||(E6(this),this.ue=a,this.g.fn(this),this.g.pe(4))};
g.h.cancel=function(){this.Jg=!0;E6(this)};
g.h.gL=function(){this.Oi=null;var a=(0,g.D)();0<=a-this.Qs?(2!=this.Sh&&this.g.pe(3),E6(this),this.fg=2,B6(18),F6(this)):K6(this,this.Qs-a)};
g.h.getLastError=function(){return this.fg};g.h=Q6.prototype;g.h.Ip=null;g.h.Bd=null;g.h.xn=!1;g.h.Ov=null;g.h.Rl=null;g.h.yq=null;g.h.Jp=null;g.h.Yd=null;g.h.vf=-1;g.h.Ej=null;g.h.Xi=null;g.h.connect=function(a){this.Jp=a;a=R6(this.g,null,this.Jp);B6(3);this.Ov=(0,g.D)();var b=this.g.D;null!=b?(this.Ej=b[0],(this.Xi=b[1])?(this.Yd=1,S6(this)):(this.Yd=2,U6(this))):(B5(a,"MODE","init"),this.Bd=new v6(this,void 0,void 0,void 0),this.Bd.Tg=this.Ip,y6(this.Bd,a,!1,null,!0),this.Yd=0)};
g.h.fC=function(a){if(a)this.Yd=2,U6(this);else{B6(4);var b=this.g;b.Ge=b.Vf.vf;n7(b,9)}a&&this.pe(2)};
g.h.fp=function(a){return this.g.fp(a)};
g.h.abort=function(){this.Bd&&(this.Bd.cancel(),this.Bd=null);this.vf=-1};
g.h.Nv=function(){return!1};
g.h.Iy=function(a,b){this.vf=a.Fj;if(0==this.Yd)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ge=this.vf;n7(c,2);return}this.Ej=c[0];this.Xi=c[1]}else c=this.g,c.Ge=this.vf,n7(c,2);else if(2==this.Yd)if(this.xn)B6(7),this.yq=(0,g.D)();else if("11111"==b){if(B6(6),this.xn=!0,this.Rl=(0,g.D)(),c=this.Rl-this.Ov,!g.Od||g.pd(10)||500>c)this.vf=200,this.Bd.cancel(),B6(12),T6(this.g,this,!0)}else B6(8),this.Rl=this.yq=(0,g.D)(),this.xn=!1};
g.h.fn=function(){this.vf=this.Bd.Fj;if(this.Bd.ue)0==this.Yd?this.Xi?(this.Yd=1,S6(this)):(this.Yd=2,U6(this)):2==this.Yd&&((!g.Od||g.pd(10)?!this.xn:200>this.yq-this.Rl)?(B6(11),T6(this.g,this,!1)):(B6(12),T6(this.g,this,!0)));else{0==this.Yd?B6(9):2==this.Yd&&B6(10);var a=this.g;this.Bd.getLastError();a.Ge=this.vf;n7(a,2)}};
g.h.Ik=function(){return this.g.Ik()};
g.h.isActive=function(){return this.g.isActive()};
g.h.pe=function(a){this.g.pe(a)};g.h=V6.prototype;g.h.lj=null;g.h.xd=null;g.h.Rb=null;g.h.Hp=null;g.h.Tl=null;g.h.iu=null;g.h.gm=null;g.h.nk=0;g.h.gH=0;g.h.Tc=null;g.h.ag=null;g.h.hf=null;g.h.Og=null;g.h.Vf=null;g.h.bo=null;g.h.bi=-1;g.h.uw=-1;g.h.Ge=-1;g.h.Nh=0;g.h.Hh=0;g.h.Kg=8;var o7=new g.Tf;g.A(W6,g.tf);g.A(X6,g.tf);g.A(Y6,g.tf);g.h=V6.prototype;g.h.connect=function(a,b,c,d,e){B6(0);this.Hp=b;this.lj=c||{};d&&g.Ca(e)&&(this.lj.OSID=d,this.lj.OAID=e);this.A?(L6((0,g.y)(this.zu,this,a),100),d7(this)):this.zu(a)};
g.h.zu=function(a){this.Vf=new Q6(this);this.Vf.Ip=null;this.Vf.i=this.u;this.Vf.connect(a)};
g.h.Nv=function(){return 0==this.g};
g.h.Ny=function(a){this.ag=null;i7(this,a)};
g.h.My=function(){this.hf=null;this.Rb=new v6(this,this.l,"rpc",this.B);this.Rb.Tg=null;this.Rb.Kp=0;var a=this.iu.clone();g.jn(a,"RID","rpc");g.jn(a,"SID",this.l);g.jn(a,"CI",this.bo?"0":"1");g.jn(a,"AID",this.bi);$6(this,a);if(!g.Od||g.pd(10))g.jn(a,"TYPE","xmlhttp"),y6(this.Rb,a,!0,this.gm,!1);else{g.jn(a,"TYPE","html");var b=this.Rb,c=!!this.gm;b.Sh=3;b.eg=A5(a.clone());J6(b,c)}};
g.h.Iy=function(a,b){if(0!=this.g&&(this.Rb==a||this.xd==a))if(this.Ge=a.Fj,this.xd==a&&3==this.g)if(7<this.Kg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ka(c)&&3==c.length)if(0==c[0])a:{if(!this.hf){if(this.Rb)if(this.Rb.xi+3E3<this.xd.xi)e7(this),this.Rb.cancel(),this.Rb=null;else break a;l7(this);B6(19)}}else this.uw=c[1],0<this.uw-this.bi&&37500>c[2]&&this.bo&&0==this.Hh&&!this.Og&&(this.Og=L6((0,g.y)(this.KH,this),6E3));else n7(this,11)}else b!=wra.yN.g&&n7(this,11);else if(this.Rb==a&&
e7(this),!g.vb(b)){c=this.u.parse(b);g.Ka(c);for(var d=0;d<c.length;d++){var e=c[d];this.bi=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.gm=e[2],e=e[3],null!=e?this.Kg=e:this.Kg=6,this.g=3,this.Tc&&this.Tc.tu(),this.iu=R6(this,this.Ik()?this.gm:null,this.Hp),j7(this)):"stop"==e[0]&&n7(this,7):3==this.g&&("stop"==e[0]?n7(this,7):"noop"!=e[0]&&this.Tc&&this.Tc.ru(e),this.Hh=0)}}};
g.h.KH=function(){null!=this.Og&&(this.Og=null,this.Rb.cancel(),this.Rb=null,l7(this),B6(20))};
g.h.fn=function(a){if(this.Rb==a){e7(this);this.Rb=null;var b=2}else if(this.xd==a)this.xd=null,b=1;else return;this.Ge=a.Fj;if(0!=this.g)if(a.ue)1==b?(b=(0,g.D)()-a.xi,o7.dispatchEvent(new X6(o7,a.oh?a.oh.length:0,b,this.Nh)),c7(this),this.o.length=0):j7(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ge)){if(d=1==b)this.xd||this.ag||1==this.g||2<=this.Nh?d=!1:(this.ag=L6((0,g.y)(this.Ny,this,a),k7(this,this.Nh)),this.Nh++,d=!0);d=!(d||2==b&&l7(this))}if(d)switch(c){case 1:n7(this,
5);break;case 4:n7(this,10);break;case 3:n7(this,6);break;case 7:n7(this,12);break;default:n7(this,2)}}};
g.h.xC=function(a){if(!g.Za(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.fM=function(a){a?B6(2):(B6(1),m7(this,8))};
g.h.fp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new K5;a.R=!1;return a};
g.h.isActive=function(){return!!this.Tc&&this.Tc.isActive(this)};
g.h.pe=function(a){o7.dispatchEvent(new Y6(o7,a))};
g.h.Ik=function(){return!(!g.Od||g.pd(10))};
g.h=p7.prototype;g.h.tu=function(){};
g.h.ru=function(){};
g.h.qu=function(){};
g.h.To=function(){};
g.h.ov=function(){return{}};
g.h.isActive=function(){return!0};g.A(q7,g.H);g.h=q7.prototype;g.h.OK=function(){this.Vc=Math.min(3E5,2*this.Vc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Vc+15E3*Math.random();g.xo(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Vc=5E3};g.A(r7,p7);g.h=r7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Df=function(a){return this.l.Ug(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.Za||(this.Za=!0,g.rf(this.l),s7(this),g.rf(this.i),this.i=null)};
g.h.ea=function(){return this.Za};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Tc=null);d.Tc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.bi):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.dc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):t7(this)&&f7(this.g,c)};
g.h.tu=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)f7(this.g,a[b])}this.N("handlerOpened")};
g.h.qu=function(a){var b=2==a&&401==this.g.Ge;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.To=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.ov=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.dc(a,this.u);return a};
g.h.ru=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),b7(this.g)):this.N("handlerMessage",new mqa(a[0],a[1]))};
g.h.KL=function(){this.i.isActive();var a=this.g,b=0;a.Rb&&b++;a.xd&&b++;0==b&&this.connect(this.u,this.o)};u7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
u7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
u7.prototype.u=function(a){a(Error("request timed out"))};var sqa=(0,g.D)(),z7=null,D7=Array(50),C7=-1,E7=!1;g.A(F7,g.Q);F7.prototype.Hd=function(){return this.g};
F7.prototype.contains=function(a){return!!$5(this.g,a)};
F7.prototype.get=function(a){return a?a6(this.g,a):null};
F7.prototype.info=function(a){B7(this.B,a)};g.A(H7,g.Q);var xra=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=H7.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.TA()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.aq(this.za),this.za=NaN)};
g.h.T=function(){this.stop();H7.Ha.T.call(this)};
g.h.TA=function(){this.za=NaN;this.g=g.Wq(v7(this.A,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.y)(this.CM,this),onError:(0,g.y)(this.BM,this),pd:(0,g.y)(this.DM,this)})};
g.h.CM=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new T5(c))};
g.h.BM=function(a){this.g=null;a.status&&404==a.status?this.i>=xra.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=xra[this.i],this.za=g.Zp((0,g.y)(this.TA,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.DM=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};g.A(J7,F7);g.h=J7.prototype;g.h.start=function(){I7(this)&&this.N("screenChange");!g.xt("yt-remote-lounge-token-expiration")&&K7(this);g.aq(this.i);this.i=g.Zp((0,g.y)(this.start,this),1E4)};
g.h.add=function(a,b){I7(this);G7(this,a);L7(this,!1);this.N("screenChange");b(a);a.token||K7(this)};
g.h.remove=function(a,b){var c=I7(this);uqa(this,a)&&(L7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.Xn=function(a,b,c,d){var e=I7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,L7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.T=function(){g.aq(this.i);J7.Ha.T.call(this)};
g.h.eD=function(a){I7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}L7(this,!b);b&&B7(this.B,"Missed "+b+" lounge tokens.")};
g.h.dD=function(a){B7(this.B,"Requesting lounge tokens failed: "+a)};g.A(N7,g.Q);g.h=N7.prototype;g.h.start=function(){var a=parseInt(g.xt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?Q7(this):(this.o=(0,g.D)()+3E5,g.wt("yt-remote-fast-check-period",this.o),this.Rr())};
g.h.isEmpty=function(){return g.Wb(this.g)};
g.h.update=function(){M7("Updating availability on schedule.");var a=this.A(),b=g.Kb(this.g,function(c,d){return c&&!!a6(a,d)},this);
P7(this,b)};
g.h.T=function(){g.aq(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);N7.Ha.T.call(this)};
g.h.Rr=function(){g.aq(this.l);this.l=NaN;this.i&&this.i.abort();var a=R7(this);if(N5(a)){var b=v7(this.u,"/pairing/get_screen_availability");this.i=w7(this.u,b,{lounge_token:g.Qb(a).join(",")},(0,g.y)(this.sK,this,a),(0,g.y)(this.rK,this))}else P7(this,{}),Q7(this)};
g.h.sK=function(a,b){this.i=null;var c=g.Qb(R7(this));if(g.qb(c,g.Qb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;P7(this,d);Q7(this)}else this.Jb("Changing Screen set during request."),this.Rr()};
g.h.rK=function(a){this.Jb("Screen availability failed: "+a);this.i=null;Q7(this)};
g.h.Jb=function(a){B7("OnlineScreenService",a)};g.A(S7,F7);g.h=S7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Xn=function(a,b,c,d){this.l.contains(a)?this.l.Xn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,B7(this.B,a),d(Error(a)))};
g.h.Hd=function(a){return a?this.g:g.eb(this.g,(0,g.ae)(this.o,function(b){return!this.contains(b)},this))};
g.h.UA=function(){return(0,g.ae)(this.Hd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.VA=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new H7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.y)(function(k){g.rf(f);d(T7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.rf(f);e(k)});
f.start();return(0,g.y)(f.stop,f)};
g.h.FM=function(a,b,c,d){g.Wq(v7(this.A,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.y)(function(e,f){var k=new T5(f.screen||{});if(!k.name||zqa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);zqa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(T7(this,k))},this),
onError:(0,g.y)(function(e){d(Error("pairing request failed: "+e.status))},this),
pd:(0,g.y)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.rf(this.l);g.rf(this.i);S7.Ha.T.call(this)};
g.h.nD=function(){Aqa(this);this.N("screenChange");this.i.update()};
S7.prototype.dispose=S7.prototype.dispose;g.A(V7,g.Q);g.h=V7.prototype;g.h.gn=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Kd=function(a){this.ea()||(a&&W7(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){B7(this.P,a)};
g.h.XA=function(){return null};
g.h.es=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.y)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.y)(function(){W7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.es("");V7.Ha.T.call(this)};g.A(X7,V7);g.h=X7.prototype;g.h.ds=function(a){if(this.g){if(this.g==a)return;W7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Cqa(this)};
g.h.di=function(a){this.info("launchWithParams no-op for Cast: "+g.Og(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.y)(function(){this.Kd()},this),(0,g.y)(function(){this.Kd(Error("Failed to stop receiver app."))},this)):this.Kd(Error("Stopping cast device witout session."))};
g.h.es=g.Ga;g.h.T=function(){this.info("disposeInternal");g.aq(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;X7.Ha.T.call(this)};
g.h.rL=function(a,b){if(!this.ea())if(b){var c=P5(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Og(c));switch(d){case "mdxSessionStatus":Bqa(this,c.screenId);break;default:W7(this,"Unknown youtube message: "+d)}}else W7(this,"Unable to parse message.")}else W7(this,"No data in message.")};
g.h.Gv=function(a,b,c,d){yqa(this.F,this.i.label,a,this.i.friendlyName,(0,g.y)(function(e){e?b(e):0<=d?(W7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Zp((0,g.y)(this.Gv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.XA=function(){return this.g};
g.h.GM=function(a){this.ea()||a||(W7(this,"Cast session died."),this.Kd())};g.A(Y7,V7);g.h=Y7.prototype;g.h.ds=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.di=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Ga;g.aq(this.A);this.o?this.o.stop((0,g.y)(this.Kd,this,null),(0,g.y)(this.Kd,this,"Failed to stop DIAL device.")):this.Kd()};
g.h.T=function(){this.g();this.g=g.Ga;g.aq(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;Y7.Ha.T.call(this)};
g.h.JM=function(a){this.ea()||a||(W7(this,"DIAL session died."),this.g(),this.g=g.Ga,this.Kd())};
g.h.Xp=function(a){this.H=Z5();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,Eqa(this));a(b);Dqa(this)}else this.B=(0,g.y)(function(){g.aq(this.A);this.B=g.Ga;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Eqa(this));a(c);Dqa(this)},this),this.A=g.Zp((0,g.y)(function(){this.B()},this),100)};
g.h.KD=function(a,b,c){yqa(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.y)(function(d){d&&d.token?(this.gn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Xp(b,c)},this),(0,g.y)(function(d){W7(this,"Failed to get DIAL screen: "+d);
this.Xp(b,c)},this))};g.A(Z7,V7);Z7.prototype.stop=function(){this.Kd()};
Z7.prototype.ds=g.Ga;Z7.prototype.di=function(){g.aq(this.g);this.g=NaN;var a=a6(this.F.Hd(),this.i.label);a?this.gn(a):this.Kd(Error("No such screen"))};
Z7.prototype.T=function(){g.aq(this.g);this.g=NaN;Z7.Ha.T.call(this)};g.A($7,g.Q);g.h=$7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.y)(this.Ky,this),(0,g.y)(this.aK,this),d,e);c.customDialLaunchCallback=(0,g.y)(this.kI,this);chrome.cast.initialize(c,(0,g.y)(function(){this.ea()||
(chrome.cast.addReceiverActionListener(this.o),pqa(),this.i.subscribe("onlineScreenChange",(0,g.y)(this.WA,this)),this.l=Gqa(this),chrome.cast.setCustomReceivers(this.l,g.Ga,(0,g.y)(function(f){this.Jb("Failed to set initial custom receivers: "+g.Og(f))},this)),this.N("yt-remote-cast2-availability-change",b8(this)),b(!0))},this),(0,g.y)(function(f){this.Jb("Failed to initialize API: "+g.Og(f));
b(!1)},this))};
g.h.TL=function(a,b){a8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)a8("Unsetting old screen status: "+this.g.i.friendlyName),c8(this,null)}if(a&&b){if(!this.g){c=a6(this.i.Hd(),a);if(!c){a8("setConnectedScreenStatus: Unknown screen.");return}var d=Fqa(this,c);d||(a8("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ga,(0,g.y)(function(e){this.Jb("Failed to set initial custom receivers: "+g.Og(e))},this)));
a8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);c8(this,new Z7(this.i,d),!0)}this.g.es(b)}else a8("setConnectedScreenStatus: no screen.")};
g.h.UL=function(a){this.ea()?this.Jb("Setting connection data on disposed cast v2"):this.g?this.g.di(a):this.Jb("Setting connection data without a session")};
g.h.IM=function(){this.ea()?this.Jb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),c8(this,null)):a8("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.y)(this.Ky,this),(0,g.y)(this.xK,this))};
g.h.T=function(){this.i.unsubscribe("onlineScreenChange",(0,g.y)(this.WA,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.bb(g.x("yt.mdx.remote.debug.handlers_")||[],x7);g.rf(this.g);$7.Ha.T.call(this)};
g.h.Jb=function(a){B7("Controller",a)};
g.h.Ly=function(a,b){this.g==a&&(b||c8(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.WJ=function(a,b){if(!this.ea())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),a8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)a8("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{a8("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:c8(this,
new Z7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:c8(this,new Y7(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:c8(this,new X7(this.i,a));break;default:this.Jb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Jb("Stopping receiver w/o session: "+a.friendlyName)}else this.Jb("onReceiverAction_ called without receiver.")};
g.h.kI=function(a){if(this.ea())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Jb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Jb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return a8("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Jb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);c8(this,new Y7(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.y)(b.KD,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.y)(b.Xp,b))};
g.h.Ky=function(a){if(!this.ea()){a8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)a8("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),c8(this,new X7(this.i,b),!0);else{this.Jb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=a6(this.i.Hd(),c.label);d&&U5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(a8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.rf(this.g),this.g=new X7(this.i,b),this.g.subscribe("sessionScreen",(0,g.y)(this.Ly,this,this.g)),this.g.di(null));this.g.ds(a)}}};
g.h.HM=function(){return this.g?this.g.XA():null};
g.h.xK=function(a){this.ea()||(this.Jb("Failed to estabilish a session: "+g.Og(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&c8(this,null))};
g.h.aK=function(a){a8("Receiver availability updated: "+a);if(!this.ea()){var b=b8(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;b8(this)!=b&&this.N("yt-remote-cast2-availability-change",b8(this))}};
g.h.WA=function(){this.ea()||(this.l=Gqa(this),a8("Updating custom receivers: "+g.Og(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ga,(0,g.y)(function(){this.Jb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",b8(this)))};
$7.prototype.setLaunchParams=$7.prototype.UL;$7.prototype.setConnectedScreenStatus=$7.prototype.TL;$7.prototype.stopSession=$7.prototype.IM;$7.prototype.getCastSession=$7.prototype.HM;$7.prototype.requestSession=$7.prototype.requestSession;$7.prototype.init=$7.prototype.init;$7.prototype.dispose=$7.prototype.dispose;var i8=[];n8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";o8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Ie=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
n8.prototype.isAdPlaying=function(){return 1081==this.playerState};
n8.prototype.getDuration=function(){return this.u?this.D+p8(this):this.D};
n8.prototype.clone=function(){return new n8(t8(this))};g.A(v8,g.Q);g.h=v8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ga,B8(this,"play")):A8(this,"play"),z8(this,1,r8(w8(this))),this.N("remotePlayerChange")):x8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ga,B8(this,"pause")):A8(this,"pause"),z8(this,2,r8(w8(this))),this.N("remotePlayerChange")):x8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=w8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ga,B8(this,"seekTo",{newTime:a}))}else A8(this,"seekTo",{newTime:a});z8(this,3,a);this.N("remotePlayerChange")}else x8(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ga,B8(this,"stopVideo")):A8(this,"stopVideo");var a=w8(this);a.index=-1;a.videoId="";o8(a);y8(this,a);this.N("remotePlayerChange")}else x8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=w8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.y)(function(){B7("CP","set receiver volume: "+d)},this),(0,g.y)(function(){this.Jb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.y)(function(){B7("CP","set receiver muted: "+b)},this),(0,g.y)(function(){this.Jb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);A8(this,"setVolume",e)}c.muted=b;c.volume=a;y8(this,c)}else x8(this,g.Qa(this.setVolume,a,b))};
g.h.Wz=function(a,b){if(1==this.g){var c=w8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Og(b.style),g.dc(d,c.g));A8(this,"setSubtitlesTrack",d);y8(this,c)}else x8(this,g.Qa(this.Wz,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();A8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=w8(this);d.audioTrackId=c;y8(this,d)}else x8(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=w8(this);c=c||0;var m={videoId:a,currentIndex:c};s8(l,a,c);g.Ca(b)&&(q8(l,b),m.currentTime=b);g.Ca(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Og(k));A8(this,"setPlaylist",m);d||y8(this,l)};
g.h.qn=function(a,b){if(1==this.g){if(a&&b){var c=w8(this);s8(c,a,b);y8(this,c)}A8(this,"previous")}else x8(this,g.Qa(this.qn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=w8(this);s8(c,a,b);y8(this,c)}A8(this,"next")}else x8(this,g.Qa(this.nextVideo,a,b))};
g.h.Ru=function(){1==this.g?A8(this,"dismissAutoplay"):x8(this,this.Ru)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}v8.Ha.dispose.call(this)};
g.h.T=function(){Tqa(this);this.o=null;this.u.clear();u8(this,null);v8.Ha.T.call(this)};
g.h.Ts=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.TJ=function(a,b){this.N(a,b)};
g.h.QH=function(a){if(!a)this.qk(null),u8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=w8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)B7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,y8(this,b)}};
g.h.qk=function(a){B7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),Uqa(this),this.N("remotePlayerChange")};
g.h.PH=function(a){a?(Uqa(this),this.N("remotePlayerChange")):this.qk(null)};
g.h.Ds=function(){A8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.cI=function(){var a=Qqa();a&&u8(this,a)};
g.h.Jb=function(a){B7("CP",a)};g.A(C8,g.Q);g.h=C8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ca(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ca(k)&&(l.currentIndex=k);c&&(this.Qa.listId=c);this.Qa.videoId=d;this.Qa.index=k||0;this.Qa.state=3;q8(this.Qa,m);this.o="UNSUPPORTED";D8("Connecting with setPlaylist and params: "+g.Og(l));this.g.connect({method:"setPlaylist",
params:g.Og(l)},a,g6())}else D8("Connecting without params"),this.g.connect({},a,g6());Wqa(this)};
g.h.dispose=function(){this.ea()||(this.N("beforeDispose"),E8(this,3));C8.Ha.dispose.call(this)};
g.h.T=function(){F8(this);H8(this);G8(this);g.aq(this.F);this.F=NaN;g.aq(this.H);this.H=NaN;this.l=null;g.ds(this.O);this.O.length=0;this.g.dispose();C8.Ha.T.call(this);this.o=this.B=this.i=this.Qa=this.g=null};
g.h.XC=function(){this.A(2)};
g.h.UH=function(){D8("Channel opened");this.M&&(this.M=!1,G8(this),this.P=g.Zp((0,g.y)(function(){D8("Timing out waiting for a screen.");this.A(1)},this),15E3));
gqa(nqa(this.g),this.V)};
g.h.RH=function(){D8("Channel closed");isNaN(this.u)?j6(!0):j6();this.dispose()};
g.h.SH=function(a){j6();isNaN(this.D())?(D8("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,D8("Channel error: "+a+" with reconnection in "+this.D()+" ms"),E8(this,2))};
g.h.TH=function(a){a.params?D8("Received: action="+a.action+", params="+g.Og(a.params)):D8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=P5(a.params.devices);this.i=(0,g.G)(a,function(c){return new S5(c)});
a=!!g.Wa(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Zqa(this,a);break;case "loungeScreenDisconnected":g.cb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Zqa(this,!1);break;case "remoteConnected":var b=new S5(P5(a.params.device));g.Wa(this.i,function(c){return b?c.id==b.id:!1})||Vpa(this.i,b);
break;case "remoteDisconnected":b=new S5(P5(a.params.device));g.cb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":ara(this,a);break;case "nowPlaying":cra(this,a);break;case "onStateChange":bra(this,a);break;case "onAdStateChange":dra(this,a);break;case "onVolumeChanged":era(this,a);break;case "onSubtitlesTrackChanged":$qa(this,a);break;case "nowAutoplaying":fra(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.B=a.params.videoId||null;this.N("autoplayUpNext",this.B);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":gra(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:D8("Unrecognized action: "+a.action)}};
g.h.HL=function(){if(this.l){var a=this.l;this.l=null;this.Qa.videoId!=a&&I8(this,"getNowPlaying")}};
C8.prototype.subscribe=C8.prototype.subscribe;C8.prototype.unsubscribeByKey=C8.prototype.Df;C8.prototype.ca=function(){var a=3;this.ea()||(a=0,isNaN(this.D())?t7(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
C8.prototype.getProxyState=C8.prototype.ca;C8.prototype.A=function(a){D8("Disconnecting with "+a);F8(this);this.N("beforeDisconnect",a);1==a&&j6();s7(this.g,a);this.dispose()};
C8.prototype.disconnect=C8.prototype.A;C8.prototype.X=function(){var a=this.Qa;this.l&&(a=this.Qa.clone(),s8(a,this.l,a.index));return t8(a)};
C8.prototype.getPlayerContextData=C8.prototype.X;
C8.prototype.ka=function(a){var b=new n8(a);b.videoId&&b.videoId!=this.Qa.videoId&&(this.l=b.videoId,g.aq(this.F),this.F=g.Zp((0,g.y)(this.HL,this),5E3));var c=[];this.Qa.listId==b.listId&&this.Qa.videoId==b.videoId&&this.Qa.index==b.index||c.push("remoteQueueChange");this.Qa.playerState==b.playerState&&this.Qa.volume==b.volume&&this.Qa.muted==b.muted&&r8(this.Qa)==r8(b)&&g.Og(this.Qa.g)==g.Og(b.g)||c.push("remotePlayerChange");this.Qa.reset(a);(0,g.B)(c,function(d){this.N(d)},this)};
C8.prototype.setPlayerContextData=C8.prototype.ka;C8.prototype.R=function(){var a=this.g.A.id,b=g.Wa(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
C8.prototype.getOtherConnectedRemoteId=C8.prototype.R;C8.prototype.D=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
C8.prototype.getReconnectTimeout=C8.prototype.D;C8.prototype.ba=function(){return this.o||"UNSUPPORTED"};
C8.prototype.getAutoplayMode=C8.prototype.ba;C8.prototype.Z=function(){return this.B||""};
C8.prototype.getAutoplayVideoId=C8.prototype.Z;C8.prototype.va=function(){if(!isNaN(this.D())){var a=this.g.i;g.yo(a.g);a.start()}};
C8.prototype.reconnect=C8.prototype.va;C8.prototype.ia=function(a,b){I8(this,a,b);Yqa(this)};
C8.prototype.sendMessage=C8.prototype.ia;g.A(J8,F7);g.h=J8.prototype;g.h.Hd=function(a){return this.Hc.$_gs(a)};
g.h.contains=function(a){return!!this.Hc.$_c(a)};
g.h.get=function(a){return this.Hc.$_g(a)};
g.h.start=function(){this.Hc.$_st()};
g.h.add=function(a,b,c){this.Hc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Hc.$_r(a,b,c)};
g.h.Xn=function(a,b,c,d){this.Hc.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.i.length;a<b;++a)this.Hc.$_ubk(this.i[a]);this.i.length=0;this.Hc=null;J8.Ha.T.call(this)};
g.h.EM=function(){this.N("screenChange")};
g.h.xJ=function(){this.N("onlineScreenChange")};
S7.prototype.$_st=S7.prototype.start;S7.prototype.$_gspc=S7.prototype.FM;S7.prototype.$_gsppc=S7.prototype.VA;S7.prototype.$_c=S7.prototype.contains;S7.prototype.$_g=S7.prototype.get;S7.prototype.$_a=S7.prototype.add;S7.prototype.$_un=S7.prototype.Xn;S7.prototype.$_r=S7.prototype.remove;S7.prototype.$_gs=S7.prototype.Hd;S7.prototype.$_gos=S7.prototype.UA;S7.prototype.$_s=S7.prototype.subscribe;S7.prototype.$_ubk=S7.prototype.Df;var K8=null,L8=null,$8=null,P8=[];g.t(a9,g.H);g.h=a9.prototype;
g.h.T=function(){g.H.prototype.T.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.Hy,this);this.g.unsubscribe("remotePlayerChange",this.tk,this);this.g.unsubscribe("remoteQueueChange",this.hn,this);this.g.unsubscribe("autoplayUpNext",this.iy,this);this.g.unsubscribe("previousNextChange",this.Ey,this);this.g.unsubscribe("nowAutoplaying",this.Ay,this);this.g.unsubscribe("autoplayDismissed",this.hy,this);this.g=this.u=null};
g.h.hx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(d9(this)){if(!w8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==w8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Bj(c[0],c[1]);break;case "control_subtitles_set_track":e9(this,c[0]);break;case "control_set_audio_track":c=c[0],d9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();f9(this,0==c?void 0:c);break;case "control_seek":f9(this,c[0]);break;case "control_subtitles_set_track":e9(this,c[0]);break;case "control_set_audio_track":c=c[0],d9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.OH=function(a){this.I.TC(a)};
g.h.oM=function(a){this.hx("control_subtitles_set_track",g.Wb(a)?null:a)};
g.h.iA=function(){var a=this.i.getOption("captions","track");g.Wb(a)||e9(this,a)};
g.h.vy=function(a){if(d9(this)){this.g.unsubscribe("remotePlayerChange",this.tk,this);var b=Math.round(a.volume);a=!!a.muted;var c=w8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.tk,this)}};
g.h.OI=function(){g.Wb(this.B)||sra(this,this.B);this.D=!1};
g.h.Hy=function(a,b){this.A.stop();2==b&&this.hA()};
g.h.tk=function(){if(d9(this)){this.o.stop();var a=w8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.ym=1;break;case 1082:case 1083:this.u.ym=0;break;default:this.u.ym=-1}switch(a.playerState){case 1081:case 1:c9(this,new g.zC(8));this.gA();break;case 1085:case 3:c9(this,new g.zC(9));break;case 1083:case 0:c9(this,new g.zC(2));this.H.stop();b9(this,this.i.getVideoData().lengthSeconds);break;case 1084:c9(this,new g.zC(4));break;case 2:c9(this,new g.zC(4));b9(this,r8(a));
break;case -1:c9(this,new g.zC(64));break;case -1E3:c9(this,new g.zC(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=w8(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,sra(this,a));a=w8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.HA()}else rra(this)};
g.h.Ey=function(){this.i.N("mdxpreviousnextchange")};
g.h.hn=function(){d9(this)||rra(this)};
g.h.eC=function(){this.g.Ru()};
g.h.iy=function(a){a&&(a=g.Wq("/watch_queue_ajax",{method:"GET",Ec:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.y)(this.ZK,this)}))&&(this.M=(0,g.y)(a.abort,a))};
g.h.ZK=function(a,b){var c=new g.kB(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.Ay=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.hy=function(){this.i.N("mdxautoplaycanceled")};
g.h.uF=function(a,b){-1==w8(this.g).playerState?f9(this,a):b&&this.g.seekTo(a)};
g.h.HA=function(){if(d9(this)){var a=w8(this.g);this.l.Na(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.vy)}};
g.h.gA=function(){this.o.stop();if(!this.g.ea()){var a=w8(this.g);1==a.playerState&&c9(this,new g.zC(8));b9(this,r8(a));this.o.start()}};
g.h.hA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(g9,g.V);g9.prototype.u=function(a){ura(this,a.state)};g.t(h9,g.WT);h9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.sb(a,this.A,this),g.XT(this,(0,g.G)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.oe(this.A(a)),this.enable(!0)):this.enable(!1)};
h9.prototype.A=function(a){return a.key};
h9.prototype.ne=function(a){return"cast-selector-receiver"==a?"Cast...":this.F[a].name};
h9.prototype.Jc=function(a){g.WT.prototype.Jc.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.gb()};g.t(i9,g.TK);g.h=i9.prototype;g.h.create=function(){lra(g.cz(g.X(this.player)));this.u.push(g.fq("yt-remote-before-disconnect",this.LH,this));this.u.push(g.fq("yt-remote-connection-change",this.bK,this));this.u.push(g.fq("yt-remote-receiver-availability-change",this.Fy,this));this.u.push(g.fq("yt-remote-auto-connect",this.ZJ,this));this.u.push(g.fq("yt-remote-receiver-resumed",this.YJ,this));this.Fy()};
g.h.load=function(){this.player.cancelPlayback();g.TK.prototype.load.call(this);this.o=new a9(this,this.player,this.g);var a=(a=qra())?a.currentTime:0;var b=Z8()?new v8(U8(),void 0):null;0==a&&b&&(a=r8(w8(b)));0!=a&&this.qd(a);tra(this,this.bk,this.bk);g.WX(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.sf(this.o,this.g);this.g=this.o=null;g.TK.prototype.unload.call(this);g.WX(this.player.app,5)};
g.h.T=function(){g.gq(this.u);g.TK.prototype.T.call(this)};
g.h.Te=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.o.hx.apply(this.o,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.ym};
g.h.PC=function(){return this.loaded?this.o.suggestion:null};
g.h.Ie=function(){return this.g?w8(this.g).Ie:!1};
g.h.hasNext=function(){return this.g?w8(this.g).hasNext:!1};
g.h.qd=function(a,b){this.D=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.D};
g.h.getProgressState=function(){var a=w8(this.g),b=this.player.getVideoData();return{allowSeeking:g.R(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.fc():!a.isAdPlaying()&&this.player.fc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+p8(a):a.l,isAtLiveHead:1>=(a.u?a.i+p8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+p8(a):a.i,seekableStart:0<a.o?a.o+
p8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.qn=function(){this.g&&this.g.qn()};
g.h.LH=function(a){1==a&&(this.B=this.g?w8(this.g):null)};
g.h.bK=function(){var a=Z8()?new v8(U8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.B=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.rf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.B)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,r8(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Fy=function(){this.A=[this.i].concat(nra());var a=V8()||this.i;j9(this,a);this.player.ma("onMdxReceiversChange")};
g.h.ZJ=function(){var a=V8();j9(this,a)};
g.h.YJ=function(){this.l=V8()};
g.h.ac=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?l8():j9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&l8(),!0):!1}};
g.h.Ds=function(){this.g.Ds()};
g.h.Mb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.mV.remote=i9;})(_yt_player);
